learning_templates/learn_app/urls.py
from django.urls import path
from learn_app import views

#template tagging
app_name= 'learn_app'

urlpatterns=[
    path('relative_url_templates/',views.relative_url_templates,name='relative_url_templates'),
    path('others/',views.others,name='others'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from learn_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('learnapp/',include('learn_app.urls')),
]

learning_templates/learn_app/models.py
from django.db import models

# Create your models here.

learning_templates/learn_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict ={'text':'hello world','number':100 }
    return render(request,'learn_app/index.html',context_dict)

def others(request):
    return render(request,'learn_app/others.html')

def relative_url_templates(request):
    return render(request,'learn_app/relative_url_templates.html')

learning_templates/templates/learn_app/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
            <li><a class="navbar-link" href="{% url 'learn_app:others'%}">Otherr</a></li>
        </ul>
    </div>
</nav>

<div class="container">
    {% block body_block %}
    <!-- anything outside of this will be inherited if you extend inany other fie-->
    {% endblock %}
</div>
</body>
</html>

learning_templates/templates/learn_app/index.html
<!DOCTYPE html>
{% extends "learn_app/base.html" %}
{% block body_block %}
<h1>welcome to index</h1>
<h2>{{ text|cut:'hello' }}</h2>
{{ number|add:"99" }}
{% endblock %}

learning_templates/templates/learn_app/others.html
<!DOCTYPE html>
{% extends "learn_app/base.html" %}
{% block body_block %}
<h1>welcome to other</h1>
<h2>this is ana template inheritance</h2>
{% endblock %}

learning_templates/templates/learn_app/relative_url_templates.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>welcome to relative</h1>
<!-- start_app : other arrived from what we mention in urls.py of startapp folder-->
<a href="{% url 'learn_app:others' %}">the other page</a>
<a href="{% url 'admin:index'%}">admin link</a>
<a href="{% url 'index' %}">link to index</a>
</body>
</html>